# Generated by Django 3.2.3 on 2021-05-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=30)),
                ('logo', models.ImageField(upload_to='settings/')),
                ('description', models.TextField(max_length=500)),
                ('fb_link', models.URLField()),
                ('twitter_link', models.URLField()),
                ('Instagram_link', models.URLField()),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
