# Generated by Django 3.2.3 on 2021-06-29 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_property_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='caregory',
            new_name='category',
        ),
    ]
